# Uncomment this line to define a global platform for your project
# platform :ios, '7.1'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.1'
pod "AFNetworking", "~> 2.0"

target 'UnfoldingWord' do

end

target 'UnfoldingWordTests' do

end

